"""
Django settings for ae_web project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_BASE_DIR = os.path.realpath(os.path.join(BASE_DIR, '..'))
print PROJECT_BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4n6_i%@_btyt^938r7n_ufbzs4k3%w=q*cz)f*^$ac_$a6iu=h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['*']

LOGIN_REDIRECT_URL = '/'
# Application definition
DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

AVAILABLE_APPS = (
    'publications',
    'accounts',
    # 'rest_api',
    'pinax.eventlog',
    'maintenance'
)

THIRD_PARTY_APPS = (
    'rest_framework',
    'rest_framework.authtoken',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + AVAILABLE_APPS

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES':(
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'PAGE_SIZE': 10
}
AUTH_USER_MODEL = 'accounts.User'
# MIDDLEWARE_CLASSES = (
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#
# )

DJANGO_MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

THIRD_PARTY_MIDDLEWARE_CLASSES = ()

MIDDLEWARE_CLASSES = DJANGO_MIDDLEWARE_CLASSES + THIRD_PARTY_MIDDLEWARE_CLASSES

ROOT_URLCONF = 'ae_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(PROJECT_BASE_DIR, 'templates/')),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
    },
]

WSGI_APPLICATION = 'ae_web.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ae_automation',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'CHARSET': 'utf8',
        'COLLATION': 'utf8_general_ci',
        'TEST_CHARSET': "utf8",
        'TEST_COLLATION': "utf8_general_ci",
        'PORT': 4488

    }
}

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ae_automation',
#         'USER': 'admin',
#         'PASSWORD': 'XBzM0zb8',
#         'HOST': 'mysql-ae-auto-test.ebi.ac.uk',
#         'CHARSET': 'utf8',
#         'COLLATION': 'utf8_general_ci',
#         'TEST_CHARSET': "utf8",
#         'TEST_COLLATION': "utf8_general_ci",
#         'PORT': 4489
#     }
# }

TEST_RUNNER = 'ae_web.runtests.TestRunner'
TESTING = False
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATICFILES_DIRS = (
    os.path.join(
        PROJECT_BASE_DIR,
        'static'
    ),
)

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(PROJECT_BASE_DIR, 'static/')
STATIC_ROOT = ''
STATICFILES_DIRS = (os.path.join(PROJECT_BASE_DIR, 'static/'),)
BASE_URL = 'http://localhost/'
AUTH_USER_MODE = 'accounts.User'
